worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    # Сжатие gzip
    gzip  on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    # Редирект HTTP -> HTTPS и поддержка Let's Encrypt / ACME
    server {
        listen       80;
        server_name  obsuzhdalych.ru www.obsuzhdalych.ru;

        location /.well-known/acme-challenge/ {
            root C:/web/obsuzhdalych;
            allow all;
        }

        location / {
            return 301 https://obsuzhdalych.ru$request_uri;
        }
    }

    # HTTPS сервер obsuzhdalych.ru -> Прокси в Docker
    server {
        listen       443 ssl;
        server_name  obsuzhdalych.ru www.obsuzhdalych.ru;

        ssl_certificate      C:/nginx/ssl/obsuzhdalych.ru-crt.pem;
        ssl_certificate_key  C:/nginx/ssl/obsuzhdalych.ru-key.pem;

        ssl_protocols        TLSv1.2 TLSv1.3;
        ssl_ciphers          HIGH:!aNULL:!MD5;

        # Лимит на загрузку фото и актов в заявках
        client_max_body_size 50M;

        location / {
            # Проксируем все запросы в наш Docker-контейнер
            proxy_pass http://127.0.0.1:3000;
            proxy_http_version 1.1;

            # Поддержка WebSocket и динамических соединений
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';

            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;

            # Передача реальных IP-адресов пользователей
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;

            proxy_read_timeout 90s;
        }
    }
}