export const ROUTES = {
  HOME: '/',
  WELCOME: '/welcome',
  AUTH: {
    LOGIN: '/auth/login',
    PIN_SETUP: '/auth/pin-setup',
    PIN_ENTER: '/auth/pin-enter',
    PIN_RESET: '/auth/pin-reset',
  },
  MOBILE: {
    FEED: '/feed',
    POST_DETAILS: (id: string | number) => `/feed/${id}`,
    TICKETS: '/tickets',
    NEW_TICKET: '/tickets/new',
    TICKET_DETAILS: (id: string | number) => `/tickets/${id}`,
    VOTES: '/votes',
    VOTE_DETAILS: (id: string | number) => `/votes/${id}`,
    VOTE_STEP: (id: string | number) => `/votes/${id}/step`,
    VOTE_FINISH: (id: string | number) => `/votes/${id}/finish`,
    PROFILE: '/profile',
    HOUSE_INFO: '/profile/house',
    NOTIFICATIONS: '/notifications',
  },
  UK: {
    ROOT: '/uk',
    HOUSES: '/uk/houses',
    DASHBOARD: '/uk/dashboard',
    TICKETS: '/uk/tickets',
    TICKET_DETAILS: (id: string | number) => `/uk/tickets/${id}`,
    RESIDENTS: '/uk/residents',
    VOTES: '/uk/votes',
    VOTE_EDITOR: '/uk/votes/new',
    FEED: '/uk/feed',
    DOCUMENTS: '/uk/documents',
    JOURNAL: '/uk/journal',
    SETTINGS: '/uk/settings',
  },
} as const;
