export const PATHS = {
  HOME: '/',
  AUTH: {
    LOGIN: '/auth/login',
    PIN_SETUP: '/auth/pin-setup',
    PIN_ENTER: '/auth/pin-enter',
  },
  MOBILE: {
    FEED: '/feed',
    FEED_POST: (id: string | number) => `/feed/${id}`,
    TICKETS: '/tickets',
    TICKET_NEW: '/tickets/new',
    TICKET_DETAILS: (id: string | number) => `/tickets/${id}`,
    VOTES: '/votes',
    VOTE_DETAILS: (id: string | number) => `/votes/${id}`,
    VOTE_STEP: (id: string | number) => `/votes/${id}/step`,
    VOTE_FINISH: (id: string | number) => `/votes/${id}/finish`,
    PROFILE: '/profile',
    PROFILE_HOUSE: '/profile/house',
    PROFILE_UTILITY: '/profile/utility',
    PROFILE_SETTINGS: '/profile/settings',
    NOTIFICATIONS: '/notifications',
  },
  UK: {
    ROOT: '/uk/*',
    DASHBOARD: '/uk/dashboard',
    HOUSES: '/uk/houses',
    HOUSE_DETAILS: (id: string | number) => `/uk/houses/${id}`,
    TICKETS: '/uk/tickets',
    RESIDENTS: '/uk/residents',
    VOTES: '/uk/votes',
    VOTE_NEW: '/uk/votes/new',
    FEED: '/uk/feed',
    DOCUMENTS: '/uk/documents',
    JOURNAL: '/uk/journal',
    SETTINGS: '/uk/settings',
  },
};
